# Generated by Django 5.1.3 on 2024-11-15 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='negocio',
            name='paleta_colores',
        ),
        migrations.AddField(
            model_name='negocio',
            name='color_primario',
            field=models.CharField(default='#FFFFFF', help_text='Código hexadecimal, por ejemplo: #FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='negocio',
            name='color_secundario',
            field=models.CharField(default='#FFFFFF', help_text='Código hexadecimal, por ejemplo: #FFFFFF', max_length=7),
        ),
        migrations.AddField(
            model_name='negocio',
            name='color_terciario',
            field=models.CharField(default='#FFFFFF', help_text='Código hexadecimal, por ejemplo: #FFFFFF', max_length=7),
        ),
    ]
