# Generated by Django 5.1.3 on 2024-12-05 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_remove_negocio_paleta_colores_negocio_color_primario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='productos/'),
        ),
    ]
