# Generated by Django 5.1.3 on 2024-12-05 08:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0002_remove_negocio_paleta_colores_negocio_color_primario_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(limit_choices_to={'groups__name': 'Cliente'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PREPARANDO', 'Preparando'), ('LISTO', 'Listo para entrega'), ('ASIGNADO', 'Asignado a repartidor'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=50),
        ),
    ]
