# Generated by Django 5.1.3 on 2024-12-06 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_alter_pedido_cliente_alter_pedido_estado'),
        ('negocio', '0003_producto_imagen'),
    ]

    operations = [
    ]
