# Generated by Django 5.1.3 on 2024-12-08 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_reclamo'),
        ('negocio', '0006_cupon'),
    ]

    operations = [
    ]
