<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-12-08 03:02
=======
# Generated by Django 5.1.3 on 2024-12-08 03:50
>>>>>>> main

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_reclamo'),
        ('negocio', '0006_cupon'),
    ]

    operations = [
    ]
