# Generated by Django 5.1.3 on 2024-12-08 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0007_merge_0005_reclamo_0006_cupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='negocio',
            name='logo',
            field=models.URLField(blank=True, help_text='URL de la imagen del logo', null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.URLField(blank=True, help_text='URL de la imagen del producto', null=True),
        ),
    ]
